### ISSUE TITLE
Errors when running rails generate favicon

### ISSUE THREAD

**Issue by Apane** [RealFaviconGenerator/rails_real_favicon#11]
Hi,

Everytime I run `rails generate favicon`

I get the following error:

```
/Users/anthony/Sites/multi/config/initializers/active_merchant.rb:1:in `<top (required)>': Base#gateway_mode is deprecated in favor of Base#mode and will be removed in a future version
/Users/anthony/Sites/multi/config/initializers/aws.rb:1:in `<top (required)>': uninitialized constant AWS (NameError)
	from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.0.13/lib/rails/engine.rb:609:in `block (2 levels) in <class:Engine>'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.0.13/lib/rails/engine.rb:608:in `each'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.0.13/lib/rails/engine.rb:608:in `block in <class:Engine>'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.0.13/lib/rails/initializable.rb:30:in `instance_exec'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.0.13/lib/rails/initializable.rb:30:in `run'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.0.13/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.0.13/lib/rails/initializable.rb:44:in `each'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.0.13/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:413:in `call'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.0.13/lib/rails/initializable.rb:54:in `run_initializers'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.0.13/lib/rails/application.rb:215:in `initialize!'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.0.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
	from /Users/anthonypanepinto/Sites/multi/config/environment.rb:5:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.0.13/lib/rails/application.rb:189:in `require_environment!'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.0.13/lib/rails/commands.rb:44:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

```
I've tried adding gem aws-sdk and it still didn't help. Any ideas?

**Comment by phbernard** [comment]
"uninitialized constant AWS"? Any chance this might be related to AWS? ;-)

**Comment by Apane** [comment]
@phbernard fixed the AWS issue :) 

The below is related to the favicon gem, what is the master_picture? I thought that was what's generated by the gem.

```

ll be removed in a future version
/usr/local/rvm/gems/ruby-2.2.1/gems/rails_real_favicon-0.0.5/lib/generators/favicon_generator.rb:24:in `read': No such file or directory @ rb_sysopen - /Users/anthony/Sites/multi/app/assets/images/master_picture.png (Errno::ENOENT)
    from /usr/local/rvm/gems/ruby-2.2.1/gems/rails_real_favicon-0.0.5/lib/generators/favicon_generator.rb:24:in `generate_favicon'
    from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
    from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
    from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
    from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
    from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
    from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.0.13/lib/rails/generators.rb:156:in `invoke'
    from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.0.13/lib/rails/commands/generate.rb:11:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require'
    from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `block in require'
    from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:214:in `load_dependency'
    from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require'
    from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.0.13/lib/rails/commands.rb:48:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'

```

**Comment by Apane** [comment]
@phbernard  Fixed... realized the master picture is the one I'd like to turn into a Favicon, thgouht I had already done that with the generator but this is a new process. CLOSED!
