### ISSUE TITLE
SSL Connection Issue

### ISSUE THREAD

**Issue by bradlis7** [RealFaviconGenerator/rails_real_favicon#14]
I think there's an issue with SSL:

```
C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:923:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)
        from C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
        from C:/Ruby22-x64/lib/ruby/2.2.0/timeout.rb:73:in `timeout'
        from C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:923:in `connect'
        from C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
        from C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:852:in `start'
        from C:/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:318:in `open_http'
        from C:/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:736:in `buffer_open'
        from C:/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:211:in `block in open_loop'
        from C:/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:209:in `catch'
        from C:/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:209:in `open_loop'
        from C:/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:150:in `open_uri'
        from C:/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:716:in `open'
        from C:/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:34:in `open'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rails_real_favicon-0.0.6/lib/generators/favicon_generator.rb:66:in `block in download_file'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rails_real_favicon-0.0.6/lib/generators/favicon_generator.rb:65:in `open'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rails_real_favicon-0.0.6/lib/generators/favicon_generator.rb:65:in `download_file'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rails_real_favicon-0.0.6/lib/generators/favicon_generator.rb:55:in `download_package'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rails_real_favicon-0.0.6/lib/generators/favicon_generator.rb:34:in `block in generate_favicon'
        from C:/Ruby22-x64/lib/ruby/2.2.0/tmpdir.rb:88:in `mktmpdir'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rails_real_favicon-0.0.6/lib/generators/favicon_generator.rb:33:in `generate_favicon'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `
```

I'm on Windows 10. Ruby and rails should be the latest versions.

(BTW thanks so much for this awesome project for free!)

**Comment by phbernard** [comment]
I can't reproduce the issue (Ruby 2.2.4 on Ubuntu). 

The certificate used by RealFaviconGenerator is a regular certificate issued by RapidSSL and valid for 3 more months. It should work just fine.

Could you look for general guidance regarding certificate authentication failure with Ruby? As an alternative,  you can temporarily hack https://github.com/RealFaviconGenerator/rails_real_favicon/blob/master/lib/generators/favicon_generator.rb#L26 and replace the URL with a site you know must succeed (eg. Google, Amazon...). Do you still have the SSL error?

**Comment by bradlis7** [comment]
It would be nice if we could pass `-v` to get more details on the command line. I'll look into it a little more.

**Comment by bradlis7** [comment]
I couldn't find a more "official" way to update openssl certs. Here's how I made it work:

https://gist.github.com/fnichol/867550

**Comment by phbernard** [comment]
Ah! Great! Thank you for the feedback. I think I encountered this issue years ago on a totally different project.
