### ISSUE TITLE
Tests fail to run in Rails 5

### ISSUE THREAD

**Issue by adamniedzielski** [RealFaviconGenerator/rails_real_favicon#18]
### Steps to reproduce

1. Remove `Gemfile.lock`
2. `bundle install`
3. `rake`

### Result

```
/Users/adam/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `action_controller' for #<Rails::Application::Configuration:0x007f992be67b68> (NoMethodError)
	from /Users/adam/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-5.0.0/lib/action_view/railtie.rb:55:in `block in <class:Railtie>'
	from /Users/adam/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/adam/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `run'
	from /Users/adam/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/adam/.rbenv/versions/2.3.3/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /Users/adam/.rbenv/versions/2.3.3/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/adam/.rbenv/versions/2.3.3/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/adam/.rbenv/versions/2.3.3/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/adam/.rbenv/versions/2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /Users/adam/.rbenv/versions/2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /Users/adam/.rbenv/versions/2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/adam/.rbenv/versions/2.3.3/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /Users/adam/.rbenv/versions/2.3.3/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /Users/adam/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/adam/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/application.rb:352:in `initialize!'
	from /Users/adam/workspace/rails_real_favicon/test/dummy/config/environment.rb:5:in `<top (required)>'
	from /Users/adam/workspace/rails_real_favicon/test/test_helper.rb:4:in `require'
	from /Users/adam/workspace/rails_real_favicon/test/test_helper.rb:4:in `<top (required)>'
	from /Users/adam/workspace/rails_real_favicon/test/lib/generators/favicon_generator_test.rb:1:in `require'
	from /Users/adam/workspace/rails_real_favicon/test/lib/generators/favicon_generator_test.rb:1:in `<top (required)>'
	from /Users/adam/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb:15:in `require'
	from /Users/adam/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb:15:in `block in <main>'
	from /Users/adam/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb:4:in `select'
	from /Users/adam/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb:4:in `<main>'
```

### Possible cause

We don't require all Rails parts in the dummy application, only:

```
require 'action_view/railtie'
require 'rails/generators'
```

**Comment by phbernard** [comment]
Oops that's right.

Regarding the requirements, you mean in https://github.com/RealFaviconGenerator/rails_real_favicon/blob/master/test/dummy/config/application.rb ? As far as I can see, these are already the two required Rails components.

**Comment by adamniedzielski** [comment]
Yes, I meant this file. I think that in Rails 5 these two are not enough, because `ActionView` requires `ActionController`:

/Users/adam/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `**action_controller**' for #<Rails::Application::Configuration:0x007f992be67b68> (NoMethodError)
	from /Users/adam/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-5.0.0/lib/**action_view/railtie.rb**:55:in `block in <class:Railtie>'


I'm doing a similar thing in a slightly different way - https://github.com/adamniedzielski/tiddle/tree/master/spec. I'm not saying that it's the correct way though. I couldn't find an established pattern in other gems when I was searching for it.

**Comment by phbernard** [comment]
The gem was recently updated, tests now pass with Rails 5.1.5.
