### ISSUE TITLE
No such file or directory @ rb_sysopen when trying to generate favicons

### ISSUE THREAD

**Issue by pupeno** [RealFaviconGenerator/rails_real_favicon#42]
This is the exact error:

```$ rails generate favicon
Running via Spring preloader in process 1765
/home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rails_real_favicon-0.1.0/lib/generators/favicon_generator.rb:85:in `initialize': No such file or directory @ rb_sysopen - https://realfavicongenerator.net/files/7cb0a93013a1f5231bd06311e789ca5f315ee4a5/favicon_package_v0.16.zip (Errno::ENOENT)
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rails_real_favicon-0.1.0/lib/generators/favicon_generator.rb:85:in `open'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rails_real_favicon-0.1.0/lib/generators/favicon_generator.rb:85:in `block in download_file'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rails_real_favicon-0.1.0/lib/generators/favicon_generator.rb:84:in `open'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rails_real_favicon-0.1.0/lib/generators/favicon_generator.rb:84:in `download_file'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rails_real_favicon-0.1.0/lib/generators/favicon_generator.rb:74:in `download_package'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rails_real_favicon-0.1.0/lib/generators/favicon_generator.rb:50:in `block in generate_favicon'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/3.0.0/tmpdir.rb:96:in `mktmpdir'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rails_real_favicon-0.1.0/lib/generators/favicon_generator.rb:49:in `generate_favicon'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `block in invoke_all'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `each'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `map'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `invoke_all'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/group.rb:232:in `dispatch'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-6.1.3.1/lib/rails/generators.rb:275:in `invoke'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-6.1.3.1/lib/rails/commands/generate/generate_command.rb:26:in `perform'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-6.1.3.1/lib/rails/command/base.rb:69:in `perform'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-6.1.3.1/lib/rails/command.rb:50:in `invoke'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-6.1.3.1/lib/rails/commands.rb:18:in `<main>'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        from /home/pupeno/bestie/bin/rails:7:in `<main>'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/commands/rails.rb:6:in `call'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/command_wrapper.rb:38:in `call'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:220:in `block in serve'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/fork_tracker.rb:10:in `block in fork'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/fork_tracker.rb:10:in `block in fork'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/fork_tracker.rb:8:in `fork'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/fork_tracker.rb:8:in `fork'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/fork_tracker.rb:26:in `fork'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/fork_tracker.rb:8:in `fork'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/fork_tracker.rb:26:in `fork'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:180:in `serve'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
        from /home/pupeno/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
        from <internal:/home/pupeno/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/pupeno/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from -e:1:in `<main>'
```

I'm not sure what's wrong, whether it's my setup or something else.

**Comment by davidwessman** [comment]
@pupeno I manage to use it locally by changing from `open` to `URI.open` if you can change it locally.
Opened a PR for it in #43.
